### ISSUE TITLE
Date feature

### ISSUE THREAD

**Issue by morris817** [da-luggas/clou#1]
When I export book notes from other reading apps, I find it helpful to include the date with each highlight. While it's not strictly essential, it can be useful for reference.

Could you consider adding an optional date feature to the highlights? This could be implemented with a toggle button that is initially unchecked. When checked, a date block would appear below each highlight.

By the way, I love your app! It's incredibly helpful.

<img width="1315" alt="image" src="https://github.com/da-luggas/clou/assets/40377597/54ebaaf4-c50d-4075-9134-bdfe1dbd9de9">

**Comment by da-luggas** [comment]
Hi morris817, thanks for reaching out! I'm really you find the app helpful. The annotation creation dates are saved within Apple Book's database, so it's definitely feasible. I also think it would be a nice addition to the functionality, so I'm going to look into it.

**Comment by da-luggas** [comment]
A preliminary support for showing and exporting the dates is [here](https://github.com/da-luggas/clou/releases/tag/v0.2.0-alpha) 🥳.
It would be awesome if you could test it out. Do you think a toggle is desired or can the date be considered essential and shown by default? Also, is the time of the day important?

**Comment by morris817** [comment]
So now there is creation date with each highlight in the interface, which is amazing! But for the exporting CVS file, the format is rather strange. I guess it's supposed to be divided into 5 columns: Author, Title, Highlight, Note, and Date. But that isn't my case, and I'm unsure if I should open the file with another application.
<img width="1402" alt="Snipaste_2023-12-07_18-30-31" src="https://github.com/da-luggas/clou/assets/40377597/3597a4ad-a2f5-480e-aef9-79d591af9061">


When I initially suggested the toggle button, my intention was to allow users to copy the raw text with the date included, but not everyone would need this information. Therefore, a toggle could be necessary for ppl who wish to hide the date. So if the date is only intended for the exported file, then the toggle is unnecessary. Personally, the specific time of day isn't important at all.

I appreciate you updating this feature so quickly. 👊🏻


P.S. I discovered a minor issue: the app appears to be out of sync with the database? While testing the feature, I created several random highlights in a book and later deleted most of them, leaving only one remaining. And, all the highlights reappear when I open Clou.
<img width="1920" alt="new issue" src="https://github.com/da-luggas/clou/assets/40377597/69d0a380-5bb3-4bee-9c78-8ebfc557334b">

**Comment by da-luggas** [comment]
Usually when importing a csv into Excel, it is possible to choose the delimiter. It seems like in your case, the comma "," was selected by default. Try selecting the semicolon ";" as delimiter. In Apple Numbers, this worked automatically. I can't check how it works in Excel since I don't have a license. The reason semicolons are used is to prevent commas in books to be interpreted as delimiters.

**Comment by morris817** [comment]
I tried opening the file using Numbers, and it worked perfectly there. _So_, I'm guessing the issue is with Excel itself, not the file. Thanks.
<img width="1027" alt="Snipaste_2023-12-28_09-12-39" src="https://github.com/da-luggas/clou/assets/40377597/ed5bcf25-6c9b-4fba-9ee3-95e849d1393f">
